### ISSUE TITLE
Support TTS models

### ISSUE THREAD

**Issue by sloganking** [64bit/async-openai#133]
Text to speech via the OpenAI API was [anounced at the OpenAI DevDay, Opening Keynote](https://www.youtube.com/live/U9mJuUkhUzk?si=A0TPjfs3FsrZDOst&t=542)

https://platform.openai.com/docs/models/tts

https://platform.openai.com/docs/guides/text-to-speech

I'd be very grateful if this library would add support.

**Comment by 64bit** [comment]
Same: https://github.com/64bit/async-openai/issues/134#issuecomment-1800195205

**Comment by sloganking** [comment]
@64bit I want to try and submit feedback. But I'm not sure how to get started. Can you provide a basic example for TTS?

**Comment by sloganking** [comment]
Nevermind. I found your example here:

https://github.com/64bit/async-openai/blob/main/examples/audio-speech/src/main.rs

**Comment by sloganking** [comment]
This works great. Thanks for all the help! Closing now.
