### ISSUE TITLE
Support gpt-4-vision-preview

### ISSUE THREAD

**Issue by sloganking** [64bit/async-openai#134]
https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo

I imagine gpt-4 vision is going to have some API differences compared to normal language models that just take text instead of files. Supporting it would probably be desirable to many people however.

**Comment by 64bit** [comment]
Hey, just published DevDay released on v0.16.0. Please give it a try, if you find any issues PRs are welcome!

**Comment by pecet** [comment]
So is vision supported yet, or only TTS?

**Comment by ludberg** [comment]
How would we add something like this?
![image](https://github.com/64bit/async-openai/assets/3208326/58fc4ec2-6aa7-4473-b8c9-3e305e6b57c9)

I think I've found the corresponding code - do you have an example on how to use it?
![image](https://github.com/64bit/async-openai/assets/3208326/0b47c3b8-5597-4d0c-8866-d4d9e593ce38)

**Comment by tiderjian** [comment]
> How would we add something like this? ![image](https://private-user-images.githubusercontent.com/3208326/285118668-58fc4ec2-6aa7-4473-b8c9-3e305e6b57c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNTMzNDEsIm5iZiI6MTcwMzA1MzA0MSwicGF0aCI6Ii8zMjA4MzI2LzI4NTExODY2OC01OGZjNGVjMi02YWE3LTQ0NzMtYjhjOS0zZTMwNWU2YjU3YzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjBUMDYxNzIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWZjYTEyY2NiYjRkZDUzY2E4ZjM2Y2U4ZTM3OGFiZmI0NWRjN2RhNGY2ZmEwZDY0ZmZjYjgyYjk0ZjliNmIwNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.gBY6s8E1m-zGy0HTmEIzOmlPDHvp0gFSoqzShwRBwqk)
> 
> I think I've found the corresponding code - do you have an example on how to use it? ![image](https://private-user-images.githubusercontent.com/3208326/285119348-0b47c3b8-5597-4d0c-8866-d4d9e593ce38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNTMzNDEsIm5iZiI6MTcwMzA1MzA0MSwicGF0aCI6Ii8zMjA4MzI2LzI4NTExOTM0OC0wYjQ3YzNiOC01NTk3LTRkMGMtODg2Ni1kNGQ5ZTU5M2NlMzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjBUMDYxNzIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2VhMGEzMzJmZDJmMDAxN2JiMzY3NTdmYTU1ZWRhMzY0ZjM2N2ZjMmY3NWUxMTg4YTBlNmFiZWUyM2Y5OTgxYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WwXtrPbIEyOFvuhTwf3fTADXyVXmRGtCHHjiAwxi2sY)

`let request = CreateChatCompletionRequestArgs::default()
    .max_tokens(4096u16)
    .model("gpt-4")
    .messages([
        ChatCompletionRequestSystemMessageArgs::default()
            .content("You are a helpful assistant.")
            .build().unwrap()
            .into(),
        ChatCompletionRequestUserMessageArgs::default()
            .content(vec!(
                ChatCompletionRequestMessageContentPartTextArgs::default().text(payload.prompt).build().unwrap().into(),
ChatCompletionRequestMessageContentPartImageArgs::default().image_url(payload.image).build().unwrap().into(),
            ))
            .build().unwrap()
            .into(),
        
    ])
    .build().unwrap();`

**Comment by 64bit** [comment]
This was addressed in https://github.com/64bit/async-openai/pull/203  hence closing
