### ISSUE TITLE
Unable to request JSON chat completion due to private field

### ISSUE THREAD

**Issue by zackangelo** [64bit/async-openai#137]
`ChatCompletionResponseFormat` was introduced to support JSON output in the chat completions API, but I believe the `r#type` field should be public instead of private? Apologies if I'm missing something. Happen to open a PR if this is the case.

**Comment by 64bit** [comment]
Oh dang, thats a bug. PR is most welcome!

**Comment by 64bit** [comment]
Hello, fix for pub visibility is added in v0.16.1. 

Thank you for reporting the issue!
