### ISSUE TITLE
Tokenizer support

### ISSUE THREAD

**Issue by Dreaming-Codes** [64bit/async-openai#148]
Whenever there are updates to this library, it causes compatibility issues with tiktoken-rs. It could be better to flip the script and have this library depend on tiktoken-rs instead, especially since this library often needs changes to keep up with OpenAI API updates.

https://github.com/zurawiki/tiktoken-rs/issues/50

**Comment by 64bit** [comment]
Hey thanks for the issue and description. I dont think this fits into scope of `async-openai`.

**Comment by Dreaming-Codes** [comment]
I see your point, but carrying this out seems impractical, considering this library is updated with every OpenAI release. Unless I'm missing something, I think isn't possible to depend on a specific range of library versions.

**Comment by 64bit** [comment]
Sorry I don't have further input on this - you and zurawiki are the right subject matter experts on this.
