### ISSUE TITLE
how to change base_url?

### ISSUE THREAD

**Issue by Dooy** [64bit/async-openai#160]
base_url default is `https://api.openai.com`,
if the cultivation base_url for other?

.Env file, is it supported?

**Comment by 64bit** [comment]
Base url can configured via config:  

https://docs.rs/async-openai/latest/async_openai/config/struct.OpenAIConfig.html#method.with_api_base

Whats your use case?

**Comment by 64bit** [comment]
Think we can close this - as feature is already present
