### ISSUE TITLE
Stabilizing wasm target

### ISSUE THREAD

**Issue by ifsheldon** [64bit/async-openai#176]
Hey I finally have some free time after weeks of busy days, so I want to stabilize wasm support in async-openai. 

Do we need more examples or more tests or more features? I think we can list those here for someone who wants to help out.

**Comment by 64bit** [comment]
Wasm disucssion might get fragmented, best to continue in #102 . 
But high level I think whats requested in #102: wasm serverless workers to be working - so cloudflare workers, aws lambda etc.
