### ISSUE TITLE
Test compilation failed

### ISSUE THREAD

**Issue by ifsheldon** [64bit/async-openai#183]
When I tried to update #125 and do a full compilation including tests, I saw this line fails to compile.

https://github.com/64bit/async-openai/blob/f28303b3867b62d57722bc3867942baf6fc39bbd/async-openai/src/file.rs#L87

The error is 
<img width="837" alt="image" src="https://github.com/64bit/async-openai/assets/39153080/b6a2e230-dba3-471c-9a6c-f1f3c936d6f3">

A quick fix is 
```rust
let list_files = client.files().list("").await.unwrap();
```
but I don't know what you want to test and I see the code came from you, so probably you can fix it yourself? @64bit

**Comment by 64bit** [comment]
Dang, this is my bad. yeah anything empty works including empty `[]` for query param. 

 Tests in file.rs were to test all file related APIs. I'll add fix for this.

**Comment by 64bit** [comment]
This is fixed in https://github.com/64bit/async-openai/commit/30f8b6a326ffe89e1698f36df631adeaadf7c498
