### ISSUE TITLE
Support variable length embeddings

### ISSUE THREAD

**Issue by adri1wald** [64bit/async-openai#184]
### Describe the feature or improvement you're requesting

From the [blog on new embedding models](https://openai.com/blog/new-embedding-models-and-api-updates):

> Both of our new embedding models were trained with a technique that allows developers to trade-off performance and cost of using embeddings. Specifically, developers can shorten embeddings (i.e. remove some numbers from the end of the sequence) without the embedding losing its concept-representing properties by passing in the dimensions API parameter. For example, on the MTEB benchmark, a text-embedding-3-large embedding can be shortened to a size of 256 while still outperforming an unshortened text-embedding-ada-002 embedding with a size of 1536.

Based on [the API reference](https://platform.openai.com/docs/api-reference/embeddings/create), this is available via a new parameter on the embedding request called `dimensions` (optional integer).

### Additional context

I'm happy to write a PR for this.

**Comment by 64bit** [comment]
Thank you for the detailed description. PR is most welcome!

**Comment by vmg-dev** [comment]
Opened a PR for this here: https://github.com/64bit/async-openai/pull/185

**Comment by 64bit** [comment]
This is released in v0.18.2. 

Thank you all!
