### ISSUE TITLE
Initialize `Client` with custom HTTP client, config, and backoff

### ISSUE THREAD

**Issue by GabrielBianconi** [64bit/async-openai#193]
Initializing a `Client` with a custom HTTP client always requires first creating a useless `reqwest::Client` in `Client::with_config`.

This adds a bit of useless overhead due to `reqwest`'s  TLS/DNS functionality, which can be non-trivial for certain low-latency applications.

Would you be open to adding an additional method along the lines of?

```rs
impl<C: Config> Client<C> {
    /// Create client with your own HTTP client, config, and backoff 
    pub fn build(http_client: reqwest::Client, config: C, backoff: backoff::ExponentialBackoff) -> Self {
        Self {
            http_client,
            config,
            backoff,
        }
    }

...
```

**Comment by GabrielBianconi** [comment]
Great, just sent a PR #197.

During initialization, among other things, a `reqwest` client seems to initialize its TLS backend [ref](https://github.com/seanmonstar/reqwest/blob/master/src/async_impl/client.rs#L247). In certain scenarios (at least for me: tiny VM with shared core + legacy backend), this seems to take a non-trivial amount of time. I observed ~30ms earlier this week. And with the current `async-openai` implementation, it wasn't possible to easily circumvent this dummy initialization.

Thanks!

**Comment by 64bit** [comment]
I see, thank you for sharing!
