### ISSUE TITLE
Usage of std::thread::sleep inside async function in assistants example

### ISSUE THREAD

**Issue by sgopalan98** [64bit/async-openai#194]
In this [line](https://github.com/64bit/async-openai/blob/48d18e02dc8afa551cf68f7676bceda395f2f9b1/examples/assistants/src/main.rs#L145) in the assistants example, you are using std::thread::sleep - this would block the whole async runtime

**Comment by 64bit** [comment]
Thanks for the issue - PR is welcome for the fix!

This is community contributed example perhaps early in their Rust journey, but yes `tokio::time::sleep` would be better.
