### ISSUE TITLE
Add retry on 504 Gateway Time-out and "connection closed before message completed"

### ISSUE THREAD

**Issue by Christof23** [64bit/async-openai#198]
Hi, I can see that requests are retried on a 429 too many requests status code. However on other error types there are no retries. 

For example for 504 responses the response returns:
```
ERROR async_openai::error:46: failed deserialization of: <html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>openresty</center>
</body>
</html>
```

Similarly, I sometimes receive `Error: IncompleteMessage: connection closed before message completed` for some requests which are not retried. I believe this is a hyper issue: https://github.com/hyperium/hyper/issues/2136

**Comment by Christof23** [comment]
PR for the 504: https://github.com/64bit/async-openai/pull/199

**Comment by 64bit** [comment]
Hi @Christof23 ,

Thank you for the issue and PR. 

What rationale is there to retry when API is down - and could potentially be [down for hours until incident is resolved](https://status.openai.com/)?

**Comment by 64bit** [comment]
> Similarly, I sometimes receive Error: IncompleteMessage: connection closed before message completed for some requests which are not retried. I believe this is a hyper issue: https://github.com/hyperium/hyper/issues/2136

Based on the [comment](https://github.com/hyperium/hyper/issues/2136#issuecomment-589488526), does configuring [same parameter](https://docs.rs/reqwest/0.11.24/reqwest/struct.ClientBuilder.html#method.pool_idle_timeout) for custom `reqwest`client fix the issue?

**Comment by Christof23** [comment]
Hi @64bit, thanks for your response.

I take your point on the 504 response; however I've seen this response while other concurrent requests have gone through successfully. I'm not sure how OpenAI are configuring their infrastructure, but it seems that a 504 with their API doesn't necessarily mean the API is unavailable. 

For the reqwest client, I think I tried the fix with the client configuration, but I'll double check.

**Comment by 64bit** [comment]
Right thing to do here is contact OpenAI and report that their API is failing. Introducing retries is propagating that failure to everyone - and making library in-deterministic. 

That said, one thing that could be done in async-openai is propgate the payload causing deserialization error so that library users can decide what right action to perform. 

So  `OpenAIError::JSONDeserialize(serde_json::Error),` becomes `OpenAIError::JSONDeserialize(serde_json::Error, String),` where the `String` is payload that OpenAI responded with.
