### ISSUE TITLE
Supporting streams when running assistants

### ISSUE THREAD

**Issue by fversaci** [64bit/async-openai#205]
Hi!

Do you have any plans to support [streaming the responses from assistants](https://platform.openai.com/docs/assistants/overview/step-4-create-a-run?context=with-streaming)?

Thanks!

**Comment by 64bit** [comment]
Need to wait until available in spec: https://github.com/openai/openai-openapi/issues/208

**Comment by b0xtch** [comment]
Update here https://github.com/openai/openai-openapi/pull/209

**Comment by Tails** [comment]
The OpenAPI spec seems to have been implemented. Is there a working branch for this functionality?
