### ISSUE TITLE
Deserialize error when retrieve content

### ISSUE THREAD

**Issue by WildBench** [64bit/async-openai#210]
Error: failed to deserialize api response: expected value at line 1 column 1

The error jumps up when I tried to download a image from code-interpreter with retrieve_content. I checked the source code and it seems retrieve_content returns Result<String, OpenAIError> which might cause trouble for image files.

Following OpenAI doc (https://platform.openai.com/docs/api-reference/files/retrieve-contents), the image could be downloaded with curl.

Could you help figure out this problem? Thank you!

**Comment by 64bit** [comment]
Definitely a bug thank you for reporting, `Result<Bytes, OpenAIError>` is a potential fix. 

It seems the spec is not accurate, seems to be reflective of jsonl file examples:
<img width="584" alt="Screen Shot 2024-04-06 at 2 23 30 PM" src="https://github.com/64bit/async-openai/assets/4025962/34169d81-ce43-4112-812c-4d83c2aef4ff">

**Comment by 64bit** [comment]
Thank you for reporting the issue, fix for this is reelased in v0.23.0, hence closing
