### ISSUE TITLE
&chat_choice.delta.function_call in the function-call-stream example has been deprecated

### ISSUE THREAD

**Issue by moom-en** [64bit/async-openai#214]
If so, which one should be used instead?
![image](https://github.com/64bit/async-openai/assets/35919845/b3bc6d60-0e26-41c6-8ca5-ceec66a70405)

**Comment by frankfralick** [comment]
Use "tool_calls". They can call more than one at a time, so you have to deal with a list of possible parallel tool calls.  Look at the tool-call-stream example:

https://github.com/64bit/async-openai/blob/f70ed12e337d8ba21987cd14d7013419a75bc36a/examples/tool-call-stream/src/main.rs#L58-L98
