### ISSUE TITLE
CreateChatCompletionRequest.max_tokens should be u32

### ISSUE THREAD

**Issue by MakotoE** [64bit/async-openai#232]
[`CreateChatCompletionRequest.max_tokens`](https://docs.rs/async-openai/latest/async_openai/types/struct.CreateChatCompletionRequest.html#structfield.max_tokens) is a `Option<u16>` as of 0.23.1.

The newer models such as [gpt-4o](https://platform.openai.com/docs/models/gpt-4o) has a context window of 128,000 tokens. This context window limit is the sum of input and output tokens.

I believe the `max_tokens` field should be `Option<u32>` to allow numbers as high as 128,000.

**Comment by 64bit** [comment]
Thank you for reporting the bug, a PR is most welcome!
