### ISSUE TITLE
Format `OpenAIError::APIError` with client-friendly message

### ISSUE THREAD

**Issue by GabrielBianconi** [64bit/async-openai#238]
In `error.rs`, we have:

```rs
...
    #[error("{:?}: {}", .0.r#type, .0.message)]
    ApiError(ApiError),
...
pub struct ApiError {
    pub message: String,
    pub r#type: Option<String>,
    pub param: Option<String>,
    pub code: Option<String>,
}
...
```

The `{:?}` leads to error messages that aren't client-friendly, such as:

```
Some(\"invalid_request_error\"): This model's maximum context length is 16385 tokens. However, your messages resulted in 25015 tokens (24961 in the messages, 54 in the functions). Please reduce the length of the messages or functions.
```

Could we replace it with something more client-friendly like:

```rs
...
    #[error("{}: {}", .0.r#type. unwrap_or("unknown_error_type".to_string()), .0.message)]
    ApiError(ApiError),
...
```

Thanks!

**Comment by 64bit** [comment]
Sure, however I wouldn't put a made up type 'unknown_error_type' and instead keep it empty when absent. In addition, it makes sense to do the same for all fields for consistency.  PR is welcome!

**Comment by GabrielBianconi** [comment]
Great.

@64bit Could you clarify what you have in mind for "In addition, it makes sense to do the same for all fields of `struct ApiError` for consistency."? Do you mean adding `param` and `code`, if available? (They're not currently included, and `message` isn't optional.)

I can send a PR later.

**Comment by 64bit** [comment]
Ah yes, your interpretation is correct. Previously the message was sort of "key": "value". 
Might as well do the same for all the fields in the `struct ApiError`  once and for all..

**Comment by GabrielBianconi** [comment]
Sounds good. I'll send a PR in a few days.
