### ISSUE TITLE
Batch Requests API

### ISSUE THREAD

**Issue by cs50victor** [64bit/async-openai#239]
Is there a batch requests example? 
Is the API supported?
If not how can I help?

**Comment by kczimm** [comment]
Looks like it. See the [docs](https://docs.rs/async-openai/latest/async_openai/struct.Batches.html) on Batches.

**Comment by cs50victor** [comment]
Thanks.

**Comment by 64bit** [comment]
>  If not how can I help?

Even though crate implements batch APIs, there is no self contained example in `examples/`, if you'd like to contribute that would be a good addition. Please feel free to reopen this issue or create a new one.
