### ISSUE TITLE
VectorStores list method errors out when no stores defined for a project

### ISSUE THREAD

**Issue by vrurg** [64bit/async-openai#242]
When attempting to list vector stores of a project where no store created yet the method `list` results in:

```
Error: JSONDeserialize(Error("invalid type: null, expected a string", line: 4, column: 18))
```

Perhaps the problem is in field `data` of `ListVectorStoresResponse` is just a `Vec` whereas the API can return a JSON `null` for it. 

The proper fix would be turning the `Vec` into `Option<Vec>`, but it's a breaking change.

**Comment by 64bit** [comment]
Thanks for reporting the error. Do you mind running same example with tracing enabled? so that actual payload which was failed to deserialize is printed, please also post the payload.

**Comment by vrurg** [comment]
No problem, if I can find out how to enable it. :) I'm afraid, your help in a form of advise is needed here.

**Comment by 64bit** [comment]
Here's an example which set up tracing and library already has code to log paylod. 

https://github.com/64bit/async-openai/blob/main/examples/assistants-func-call-stream/src/main.rs#L19

(perhaps this is another opportunity for improvement where failed payload can be part of the `JSONDeserialize` variant of `OpenAIError` so its easily available - however that puts burden on the user to log it - logging in the library makes it available for everyone. perhaps having both can be a an option too)

**Comment by 64bit** [comment]
Thank you for providing the error. This means that the bug is `last_id` and `first_id` needs to be `Option`al in `ListVectorStoresResponse` 

https://github.com/64bit/async-openai/blob/main/async-openai/src/types/vector_store.rs#L108-L109
