### ISSUE TITLE
[Feature Request] Gemini support

### ISSUE THREAD

**Issue by Napolitain** [64bit/async-openai#271]
i know it is a bit "out of scope" seemingly but I think we would benefit from Gemini support using the same interface.
main api could stay identical to openai and thus not implement specifics from google
there is also some ai audio stuff in google ai (non gemini)

**Comment by 64bit** [comment]
Nobody stopping you from doing so, pretty liberal license to fork an do it.

**Comment by dashed** [comment]
You can use the Gemini models now: https://developers.googleblog.com/en/gemini-is-now-accessible-from-the-openai-library/
