### ISSUE TITLE
Add Fine Tuning Example

### ISSUE THREAD

**Issue by 64bit** [64bit/async-openai#31]
Add a standalone fine tuning example
- self contained to be able to run with single `cargo run` command. 
- supporting data for fine tuning can be part of example similar to how images are kept for [examples/create-image-variation](https://github.com/64bit/async-openai/tree/main/examples/create-image-variation)
- (Optional) use https://github.com/openai/openai-cookbook as inspiration

**Comment by Doordashcon** [comment]
Looks like this is still relevant?

**Comment by 64bit** [comment]
@Doordashcon , I do not see any Deprecated or Legacy warning on https://platform.openai.com/docs/api-reference/fine-tunes 
so relevant, yes?
