### ISSUE TITLE
Support Microsoft Azure Endpoints

### ISSUE THREAD

**Issue by 64bit** [64bit/async-openai#32]
Add support for :
- https://github.com/openai/openai-python#microsoft-azure-endpoints
- https://azure.microsoft.com/en-us/products/cognitive-services/openai-service/#overview

**Comment by 64bit** [comment]
It is GA https://azure.microsoft.com/en-us/blog/general-availability-of-azure-openai-service-expands-access-to-large-advanced-ai-models-with-added-enterprise-benefits/ 

However still limited access.

**Comment by 64bit** [comment]
Nice project! Thank you for offering to test @Kakise! 
I might attempt to implement support over weekend, and let you know when ready for testing.

Does it support all the same APIs as OpenAI? Are there any major difference you noticed other than the mechanics of API call?

**Comment by Kakise** [comment]
@64bit right now I only tested completions and embeddings but it does support all OpenAI APIs.

The main difference I noticed is how you call your model. For OpenAI it's passed in the body and for Azure it's passed in the url

**Comment by 64bit** [comment]
Hi @Kakise , thank you for your response, I had opportunity to look into this today and I discovered that only embedding, completions, and chat completions APIs are currently supported in `2023-03-15-preview` api version.

SO I have made the changes to support Azure in #67 , I have tested all the examples on OpenAI after this change. 

For testing on Azure and make it as simple for you  I have added a new example called `examples/azure-openai-service` with three API calls in it for embedding, completioins and chat completion. You will only need to change api_key, endpoint and deployment id. 

Can you please run that example and post output? I can add output to `examples/azure-openai-service/README.md`

Hope all goes well, thank you for your help on this!
