### ISSUE TITLE
Aggressive Cargo.toml dependencies cause problems

### ISSUE THREAD

**Issue by luketpeterson** [64bit/async-openai#39]
I noticed the latest release specifies minimum versions of the latest release of all dependency crates.  In some cases this crate requires a version of another crate released only a few days ago.

The problem is that some larger projects version-lock certain dependencies, and it can take them many months to migrate to the latest.  This means it's impossible to integrate async-openai into a project along-side certain other frameworks.

Obviously, when functionality from the latest version of a dependency is needed, then it's necessary to specify that dependency version, however automatically advancing to the latest version of every crate can cause a lot of unnecessary problems.

Thank you.

**Comment by 64bit** [comment]
Thank for issue and bringing this up. I agree latest dependencies versions introduced in 0.7.0 are not ideal for large projects. 

However, you could use all the same features with old dependencies of `async-openai`  including the fix in #37  by using git revision, in `Cargo.toml`:

```toml
async-openai = { git = "https://github.com/64bit/async-openai", rev = "d96faab0d0bfc24726f903e32ac38ef291c2d994"}
```

This should fix short term problem for you, in long term `0.7.0` onward is the right direction.

I agree we should be mindful of upgrading dependencies in the future if larger projects started relying on `async-openai` crate. 

Hope this should resolve issue for you?

**Comment by luketpeterson** [comment]
Thanks for the suggestion.  For now, pointing my project at a pre-release async-openai will be fine, while waiting for the other projects to adopt newer dependency versions.

I mainly filed this issue to ask that future releases not advance the minimum requirements more aggressively than is necessary.  Thanks for considering my suggestion.  I'll close this issue.

Thanks again and thanks for releasing async-openai.

**Comment by 64bit** [comment]
Upgrades will be inevitable..but having a better release management going forward would avoid problems you faced. Like releasing multiple versions to separate bug fixes, breaking changes etc. instead of bundling them together so end user has flexibility to update as they go without getting into major problems. 

I ACK your suggestion! After this avoidable diversion.. hope you get back on track to build good stuff with OpenAI :)
