### ISSUE TITLE
Allow customization of internal HTTP client

### ISSUE THREAD

**Issue by jtaox** [64bit/async-openai#47]
Hello! I'm using your  library and I noticed that there's no option to customize the internal HTTP client used for API requests when calling Client::new(). This makes it impossible to implement a proxy for all HTTP requests.

I was wondering if it would be possible to add a customization option for the internal reqwest client, similar to what the [chatgpt-api](https://github.com/transitive-bullshit/chatgpt-api/blob/main/src/chatgpt-api.ts#LL61C26-L61C26) offer. This would allow for greater flexibility and more use cases for this library.

**Comment by 64bit** [comment]
Hi @jtaox ,  happy to know you found it useful. 

Can you elaborate more about the use case with custom reqwest/HTTP client? What customization would you like to do?

I havent had to use a proxy yet, so your use case can help me understand better.

**Comment by TmLev** [comment]
@64bit sometimes you may have a misbehaving virtual machine that doesn't like certain IP addresses. In such case you can specify an HTTP proxy for `reqwest` to proxy all the requests.

**Comment by jtaox** [comment]
@64bit  In China, some websites are banned by the GFW, making it impossible to access them directly. Therefore, it's necessary to use a foreign server as a proxy to access these websites

**Comment by jtaox** [comment]
@64bit  @TmLev Thank you for your patient response. After carefully reviewing the request documentation at [proxies](https://docs.rs/reqwest/latest/reqwest/#proxies), I found that reqwest enables proxies by default, as long as the system environment variables are set correctly. Therefore, #48  does not need to be merged.

**Comment by 64bit** [comment]
Aha glad you found a solution :) 

Thank you for contributing and sharing about GFW.

I'll close this as it's resolved for you.

**Comment by TmLev** [comment]
While proxies may be set up by the means of environment variables, supporting custom middleware is still a thing :)

For instance, there is a tracing middleware which enables the use of OpenTelemetry traces: https://crates.io/crates/reqwest-tracing

**Comment by 64bit** [comment]
Hi @TmLev , Your use case is different from the original need for it, but this issue is broad enough so I'll  re-open this.

For having middlewares on client side, I see more info on https://github.com/seanmonstar/reqwest/issues/155 and https://truelayer.com/blog/adding-middleware-support-to-rust-reqwest/

So until `reqwest` natively support it, PRs are welcome, if this changes the type signature then additional work required then #48?

**Comment by TmLev** [comment]
I doubt `reqwest` will support it natively in the near future, which makes `reqwest-middleware` the only alternative (the other one is using `tower::Service` which is quite cumbersome).

Unfortunately, `reqwest-eventsource` only works with `reqwest::RequestBuilder`, so I'll need some time to glue them together.

In the meantime, I did a small optimization (which was a low-hanging fruit, really): #58

**Comment by 64bit** [comment]
Happy 1 year anniversary for this issue 😄 

I think its safe to close it, seems like having feature to provide `reqwest` client in `with_http_client` is good enough. 
Hence, closing this.

**Comment by 64bit** [comment]
Recently added Tower support in v0.37.0, decided to go with Tower instead of reqwest-middleware due to maximum flexibility to reuse tower ecosystem and maximum support for WASM.
