### ISSUE TITLE
max_tokens and user fields for CreateChatCompletionRequestArgs

### ISSUE THREAD

**Issue by Morb0** [64bit/async-openai#49]
It's seem like `max_tokens` filed is missed in args builder, but it presented in documentation:
https://platform.openai.com/docs/api-reference/chat/create

**Comment by zurawiki** [comment]
Created a fix in #50

**Comment by Morb0** [comment]
Also `user` field is missing.

**Comment by 64bit** [comment]
Thank you @zurawiki and @Morb0 for finding all the missing fields. 

Seems like they updated it https://github.com/openai/openai-openapi/commit/8b9c21f34dd76e5d1f2435c6e80b45ca0a6d2be9

**Comment by 64bit** [comment]
This is released in v0.9.1
