### ISSUE TITLE
Streaming response chunk size is incorrect

### ISSUE THREAD

**Issue by varon** [64bit/async-openai#54]
Hi,

I've been experimenting with a few libraries in different languages - I've got this working correctly, but with the streamed response, even with your own examples it seems to stream **by newlines rather than by token**. This means that the time until output is very long, introducing a large delay with a much less responsive overall feel.

Your own example has this clearly shown: (see https://raw.githubusercontent.com/64bit/async-openai/assets/completions-stream/output.svg)

Correctly implemented, the streaming should function in the same way as ChatGPT's web API. If you would like a reference on a library that implements this correctly, you can find this here: https://github.com/OkGoDoIt/OpenAI-API-dotnet#streaming

I hope you can fix this, because I'd prefer to be using rust for this project than C#!

**Comment by 64bit** [comment]
Hi @varon 

Thank you for detail explanation of the issue you were seeing, 

`async-openai` emits the content as it is when available. The behavior you saw has to do with how example implements printing it to console.  stdout is frequently line buffered by default, more about it here: https://doc.rust-lang.org/std/macro.print.html 

So I have updated the chat-stream example https://github.com/64bit/async-openai/pull/56  to make it visually similar to ChatGPT  by flusing content to terminal when its available, here's the output https://raw.githubusercontent.com/64bit/async-openai/assets/chat-stream/output.svg 

This issue will close automatically once I merge the PR #56, but please feel free to comment and/or open if you have any other issue.

**Comment by varon** [comment]
Thank you very much for this explanation and change.
