### ISSUE TITLE
Failed to deserialized

### ISSUE THREAD

**Issue by federico123579** [64bit/async-openai#61]
In a non reproducible way errors like the following occur.
```
Error: failed to deserialize api response: expected value at line 1 column 1
```

For more info, these are caused when the responses are awaited.

**Comment by 64bit** [comment]
Hi @federico123579, 

It seems that OpenAI API responding with no value where Rust deserializtion was expecting it for one the response types in `types.rs`.  So we might have to change response type to accept `Option<T>` instead. 

Can you provide info about which API call is it?

**Comment by 64bit** [comment]
Thank you, it seems `CreateChatCompletionResponse` is correctly reflecting openapi spec. 
However, looking at the response example here https://platform.openai.com/docs/api-reference/chat/create suggest that `model` field could be optional. 

Also, Chat API is currently in beta, so hard to find a solution here. 

What I'm thinking is to update `OpenAIError::JSONDeserialize` to include actual payload returned by API to make it easy to surface invalid response.

**Comment by 64bit** [comment]
As a first step, I have added `tracing::error!( ... )` calls to log actual payload when derserialization fails, that way we get more visibility into what OpenAI is responding with. #62 


Please give  `v0.10.1` a try, you might have to setup the `tracing_subscriber` to log the errors.

**Comment by mhuang74** [comment]
I ran into someting similar, and adding retries (with exponential backoff) solved my problems.

**Comment by 64bit** [comment]
That's strange, the library doesnt retry deserialization errors, one example:
https://github.com/64bit/async-openai/blob/main/async-openai/src/client.rs#L288-L290

**Comment by mhuang74** [comment]
I think openai sometimes respond with empty results that break parsing.
Hence retry helps.

**Comment by 64bit** [comment]
Closing this, hopefully no longer an issue. Please reopen with additional info with debug logs if needed.

**Comment by frozenspider** [comment]
This seems to still be the problem:
```
2025-03-13T22:50:55.037145Z ERROR async_openai::error: failed deserialization of: error code: 502

thread 'tokio-runtime-worker' panicked at /Users/fs/code/rosetta/src/llm/openai.rs:250:62:
called `Result::unwrap()` on an `Err` value: JSONDeserialize(Error("expected value", line: 1, column: 1))
```
