### ISSUE TITLE
Feature Request: Implement Serilaize on response types

### ISSUE THREAD

**Issue by djrodgerspryor** [64bit/async-openai#65]
I'm trying to cache openai responses so that my tests will produce deterministic results, but the response types defined in this library don't implement `Serialize`, so I have to maintain a copy of them which does.

Would you be open to adding `Serialize` to all of the response types? This obviously increases the amount of generated code, but it makes consuming the data in cases like mine much easier.

**Comment by 64bit** [comment]
Hi @djrodgerspryor , 

Thank you for describing your use case and also implementing it! 

So far `async-openai` has been mostly written to favor usefulness over any optimizations. So its all good.

**Comment by 64bit** [comment]
This is released in v0.10.3

**Comment by djrodgerspryor** [comment]
Thanks for the quick, helpful response!
