### ISSUE TITLE
Embedding Example

### ISSUE THREAD

**Issue by Doordashcon** [64bit/async-openai#69]
Requires Api key to create embedding but no direction as to how in the example.
https://github.com/64bit/async-openai/blob/f6b04b54d5627a18a1f3c376f878290b92ef571a/examples/embeddings/src/main.rs#L21

This can be resolved by including `.with_api_key("insert api key")`

**Comment by 64bit** [comment]
Hello @Doordashcon,

Its not specific to any example. You have to provide API key for any API calls to work which by default you can provide through `OPENAI_API_KEY` environment variable, as mentioned here https://github.com/64bit/async-openai#usage

**Comment by Doordashcon** [comment]
Oh I see, so when deploying your applications you just need to pass in the env to the hosting service. That’s great!
