### ISSUE TITLE
Use official types for chat completion stream response from spec

### ISSUE THREAD

**Issue by 64bit** [64bit/async-openai#75]
`async-openai`'s existing types for Chat stream were written from observation of OpenAI response. 

Recently (16th June 2023) officially types were update for it, and needs to be used in `async-openai` as well 
Ref: https://github.com/openai/openai-openapi/pull/48/files

`async-openai` has used the type names from spec for majority of types  - hence `ChatCompletionStreamResponseDelta` and `CreateChatCompletionStreamResponse` names should be used.

**Comment by 0xVesion** [comment]
Hey, I'd be happy to pick this one up. Please give me some pointers on how to proceed. Should I generate the types using the OpenAPI spec and replace the existing ones in src/types/types.rs?

**Comment by 64bit** [comment]
Hi Vincent,

Thank you for your interest and offering to help! Actually `async-openai`
is written by hand and is not generated for various reasons (human error in
spec - this issue is an example of such, lack of tooling at the time I
created it etc.)

For resolving this issue, it requires the following:
1 See the function signature in `chat.rs` for `create_stream` its response
type would change to the ones in
https://github.com/openai/openai-openapi/pull/48/files
2. Hence corresponding types need to be updated in `types.rs`
3. Example need to be updated with new types `examples/chat-stream`

Let me know if you need further clarification!

Thank you,
Himanshu

**Comment by Doordashcon** [comment]
Hello @64bit, looks like `CreateChatCompletionStreamResponse` up to date [here](https://github.com/64bit/async-openai/blob/b4e36716df4ba09446ac42fc1e303f6187d55865/async-openai/src/types/types.rs#L881C46-L881C46)

**Comment by 64bit** [comment]
Hi @Doordashcon , Ah pure coincidece however its field `choices`  with vector of  `ChatChoiceDelta` should be vector of `ChatCompletionStreamResponseDelta`.  ( There could be more - but I haven't parity checked with spec for this comment)

**Comment by victor-wei126** [comment]
I'm interested in contributing a solution to this issue. Is this project still active?

**Comment by 64bit** [comment]
Hi @victor-wei126 

Thank you for offering to contribute ❤️ 

Indeed the project is active, there was a new version release a few weeks ago. 

For this particular issue, I'd recommend to have latest spec from upstream repo, so you can see the diff of updated spec with the one in this repo and would help to update types as well.

**Comment by victor-wei126** [comment]
Hey @64bit ... my pleasure :) - I'm interested in AI and Rust - hope I can be helpful.

I'm going to poke around and mess with the library a bit. Once I have a better understanding, I'll get back to you. Besides this issue, are there any other particularly pressing issues?

**Comment by 64bit** [comment]
Other issues from top of my head (I have also created new issues to track them): 

1 . Function call example with streaming is needed https://github.com/64bit/async-openai/issues/85
2. Make form submissions retryable on rate limits:  https://github.com/64bit/async-openai/issues/86

**Comment by victor-wei126** [comment]
I'll take a look at both of those (sorry for clogging up this issue)

**Comment by 64bit** [comment]
No worries, all good.

**Comment by 64bit** [comment]
Resloved by #92
