### ISSUE TITLE
Update library to match OpenAI API release 2.0.0

### ISSUE THREAD

**Issue by oslfmt** [64bit/async-openai#93]
OpenAI released a new version of their API [here](https://github.com/openai/openai-openapi/releases/tag/2.0.0).

Major changes are removing deprecated endpoints as well as updating the ```CreateChatCompletionStreamResponse``` and creating ```ChatCompletionStreamResponseDelta```. Those types are brought up in #75.

**Comment by 64bit** [comment]
This is released in v0.15.0
