### ISSUE TITLE
Failed to deserialize api response: invalid type: null, expected a sequence at line 27763 column 23

### ISSUE THREAD

**Issue by turulix** [64bit/async-openai#99]
Hey!

I'm currently using this library to generate Embeddings but facing this issue when generating them in batches. With a batch size of 25
```rust
        let mut req_count = 0;
        for chunk in descriptions_for_embeddings.chunks(25) {
            req_count += 1;
            info!("Request: {}", req_count);
            let embeddings_res = OPENAI_CLIENT
                .embeddings()
                .create(CreateEmbeddingRequest {
                    model: "text-embedding-ada-002".to_string(),
                    input: EmbeddingInput::StringArray(Vec::from(chunk.clone())),
                    user: Some(ctx.task_owner.to_string()),
                })
                .await?;
            embeddings.extend(embeddings_res.data);
        }
```
But after a few requests anywhere between 12 - 16 requests this just failes for some reason. I'm definitly not hitting any ratelimits either so not sure what is causing this.

**Comment by 64bit** [comment]
Hi @turulix 

Thank you for reporting issue. If you enable tracing subscriber and get the full response object it would be useful information to identify problem.  Please see  https://github.com/64bit/async-openai/blob/async-openai-v0.13.1/async-openai/src/error.rs#L46-L49

**Comment by turulix** [comment]
Heres the raw file you asked for https://haste.turulix.de/raw/ozuxiloqob 

I assume its the embedding with the index 4 and 7 cause for some strange reason the embedding is null on those
![image](https://github.com/64bit/async-openai/assets/28957605/1f04a0bf-324a-4349-8c60-224181699aa3)

**Comment by 64bit** [comment]
Thanks for sharing the payload. Yeah this seems like OpenAI bug, their API spec mentions `embedding` is a required field. 

Right place for it would be to report it to OpenAI folks.

**Comment by turulix** [comment]
Not sure where i can report that to them

**Comment by 64bit** [comment]
I think few avenues to reach them to try:
- help.openai.com
- I think they had Discord 
- One of their repository may be openai-openapi

**Comment by 64bit** [comment]
I think we can close this, but if there anything for async-openai to do please feel free to open again or create new issue.
